
package com.simplecore.erp.client.gui.workspace.modules.financial.financialaccounting.chartofaccount.config;

/**
 * @author Michael F. Sánchez
 * @since 2024
 * @project Lyra Core+ ERP
 * @company SimpleCore Systems
 * @country Republic of Nicaragua   
 * 
 */
public enum ChartOfAccountField {

    CHART_ID("CHART.OF.ACCOUNT.CHART.ID"),
    CODE("CHART.OF.ACCOUNT.CODE"),
    NAME("CHART.OF.ACCOUNT.NAME"),
    ACCOUNT_MODEL_ID("CHART.OF.ACCOUNT.ACCOUNT.MODEL.ID"),
    ACCOUNT_MODEL_NAME("CHART.OF.ACCOUNT.ACCOUNT.MODEL.NAME"),
    CURRENCY_CODE("CHART.OF.ACCOUNT.CURRENCY.CODE"),
    COUNTRY_CODE("CHART.OF.ACCOUNT.COUNTRY.CODE"),
    BUSINESS_TYPE("CHART.OF.ACCOUNT.BUSINESS.TYPE"),
    INDUSTRY_CLASSIFICATION("CHART.OF.ACCOUNT.INDUSTRY.CLASSIFICATION"),
    FISCAL_YEAR("CHART.OF.ACCOUNT.FISCAL.YEAR"),
    FISCAL_START_DATE("CHART.OF.ACCOUNT.FISCAL.START.DATE"),
    FISCAL_END_DATE("CHART.OF.ACCOUNT.FISCAL.END.DATE"),
    ACCOUNTING_STANDARD("CHART.OF.ACCOUNT.ACCOUNTING.STANDARD"),
    STATUS("CHART.OF.ACCOUNT.STATUS"),
    MULTICURRENCY_SUPPORT("CHART.OF.ACCOUNT.MULTICURRENCY.SUPPORT"),
    TAX_SCHEMA("CHART.OF.ACCOUNT.TAX.SCHEMA"),
    VERSION_TAG("CHART.OF.ACCOUNT.VERSION.TAG"),
    NOTES("CHART.OF.ACCOUNT.NOTES"),
    DESCRIPTION("CHART.OF.ACCOUNT.DESCRIPTION"),
    CREATED_BY("CHART.OF.ACCOUNT.CREATED.BY"),
    CREATED_AT("CHART.OF.ACCOUNT.CREATED.AT"),
    UPDATED_AT("CHART.OF.ACCOUNT.UPDATED.AT"),
    SYS_TRANSACTION("CHART.OF.ACCOUNT.SYS.TRANSACTION");

    private final String key;

    ChartOfAccountField(String key) {
        this.key = key;
    }

    public String getKey() {
        return key;
    }
}
