
package com.simplecore.erp.client.gui.workspace.modules.financial.financialaccounting.account.accountingacocunt.view.list.gui;

/**
 * @author Michael F. Sánchez
 * @since 2024
 * @project Lyra Core+ ERP
 * @company SimpleCore Systems
 * @country Republic of Nicaragua   
 * 
 */
public enum AccountinAccountTableNames {
    
    AC18_ACCOUNT_FILTER_LIST_ACCOUNT_CODE("AC18.ACCOUNTING.ACCOUNT.FILTER.LIST.ACCOUNT_CODE"),
    AC18_ACCOUNT_FILTER_LIST_ACCOUNT_NAME("AC18.ACCOUNTING.ACCOUNT.FILTER.LIST.ACCOUNT_NAME"),
    AC18_ACCOUNT_FILTER_LIST_ACCOUNT_CREATED_BY("AC18.ACCOUNTING.ACCOUNT.FILTER.LIST.ACCOUNT_CREATED_BY"),
    AC18_ACCOUNT_FILTER_LIST_ACCOUNT_CREATED_AT("AC18.ACCOUNTING.ACCOUNT.FILTER.LIST.ACCOUNT_CREATED_AT"),
    AC18_ACCOUNT_FILTER_LIST_ACCOUNT_UPDATED_BY("AC18.ACCOUNTING.ACCOUNT.FILTER.LIST.ACCOUNT_UPDATED_BY"),
    AC18_ACCOUNT_FILTER_LIST_ACCOUNT_UPDATED_AT("AC18.ACCOUNTING.ACCOUNT.FILTER.LIST.ACCOUNT_UPDATED_AT"),
    AC18_ACCOUNT_FILTER_LIST_ACCOUNT_STATUS("AC18.ACCOUNTING.ACCOUNT.FILTER.LIST.ACCOUNT_STATUS"),
    AC18_ACCOUNT_FILTER_LIST_IS_CLOSED("AC18.ACCOUNTING.ACCOUNT.FILTER.LIST.IS_CLOSED"),
    AC18_ACCOUNT_FILTER_LIST_SUBCLASS_CODE("AC18.ACCOUNTING.ACCOUNT.FILTER.LIST.SUBCLASS_CODE"),
    AC18_ACCOUNT_FILTER_LIST_SUBCLASS_NAME("AC18.ACCOUNTING.ACCOUNT.FILTER.LIST.SUBCLASS_NAME"),
    AC18_ACCOUNT_FILTER_LIST_SUBCLASS_CREATED_AT("AC18.ACCOUNTING.ACCOUNT.FILTER.LIST.SUBCLASS_CREATED_AT"),
    AC18_ACCOUNT_FILTER_LIST_CLASS_ID("AC18.ACCOUNTING.ACCOUNT.FILTER.LIST.CLASS_ID"),
    AC18_ACCOUNT_FILTER_LIST_CLASS_NAME("AC18.ACCOUNTING.ACCOUNT.FILTER.LIST.CLASS_NAME"),
    AC18_ACCOUNT_FILTER_LIST_MODEL_NAME("AC18.ACCOUNTING.ACCOUNT.FILTER.LIST.MODEL_NAME"),
    AC18_ACCOUNT_FILTER_LIST_DESCRIPTION("AC18.ACCOUNTING.ACCOUNT.FILTER.LIST.DESCRIPTION"),
    AC18_ACCOUNT_FILTER_LIST_MODEL_CREATED_AT("AC18.ACCOUNTING.ACCOUNT.FILTER.LIST.MODEL_CREATED_AT"),
    AC18_ACCOUNT_FILTER_LIST_MODEL_CREATED_BY("AC18.ACCOUNTING.ACCOUNT.FILTER.LIST.MODEL_CREATED_BY"),
    AC18_ACCOUNT_FILTER_LIST_STATUS("AC18.ACCOUNTING.ACCOUNT.FILTER.LIST.STATUS"),
    AC18_ACCOUNT_FILTER_LIST_MODEL_MODIFIED_BY("AC18.ACCOUNTING.ACCOUNT.FILTER.LIST.MODEL_MODIFIED_BY"),
    AC18_ACCOUNT_FILTER_LIST_MODEL_MODIFIED_AT("AC18.ACCOUNTING.ACCOUNT.FILTER.LIST.MODEL_MODIFIED_AT"),
    AC18_ACCOUNT_FILTER_LIST_STATE("AC18.ACCOUNTING.ACCOUNT.FILTER.LIST.STATE");
    ;
    
    private final String key;

    private AccountinAccountTableNames(String key) {
        this.key = key;
    }

    public String getKey() {
        return key;
    }
    
    
}
