
package com.simplecore.erp.shared.responses.base;

/**
 * @author Michael F. Sánchez
 * @since 2024
 * @project Lyra Core+ ERP
 * @company SimpleCore Systems
 * @country Republic of Nicaragua   
 * 
 */
public enum ResponseType {
    LOGIN,
    LOGOUT,
    TRANSACTION_PERMISSIONS,
    SOCIETY_CLASS,
    SOCIETY_CLASS_LIST,
    FI_ACCOUNT_CLASS,
    FI_ACCOUNT_CLASS_BY_MODEL,
    FI_ACCOUNT_MODEL_CREATE,
    FI_ACCOUNT_MODEL_LIST,
    FI_ACCOUNT_MODEL_RETRIEVE,
    FI_ACCOUNT_RANGES_BY_MODEL_ID,
    FI_ACCOUNT_MODEL_CHANGE,
    FI_ACCOUNT_MODEL_STATE_CHANGE,
    FI_ACCOUNT_SUBCLASS_CREATE,
    FI_ACCOUNT_SUBCLASSES_RETRIEVE,
    FI_ACCOUNT_SUBCLASS_CHANGE,
    FI_ACCOUNT_SUBCLASS_DELETE,
    FI_ACCOUNTS_BY_SUBCLASS_RETRIEVE,
    FI_LAST_ACCOUNT_NUMBER_BY_PARENT,
    FI_LAST_ACCOUNT_NUMBER_BY_SUBCLASS,
    FI_ACCOUNTING_ACCOUNT_CREATE,
    FI_ACCOUNTING_ACCOUNT_CHANGE,
    FI_ACCOUNTING_ACCOUNT_RETRIEVE,
    FI_ACCOUNTING_ACCOUNT_LIST_RETRIEVE,
    FI_ACCOUNTING_ACCOUNT_FILTER_QUERY_RETRIEVE,
    FI_ACCOUNT_SUBCLASSES_LIST,
    FI_ACCOUNT_MODEL_STATES_LIST,
    SYSTEM_USERS_LIST, 
    FI_ACCOUNTING_ACCOUNT_STATUS_LIST,
    COUNTRIES_LIST,
    CURRENCIES_LIST, 
    COUNTRY_BY_CODE,
    CURRENCY_BY_CODE, 
    FI_ACCOUNTING_STANDARDS, 
    FI_CHART_OF_ACCOUNT_STATUS, 
    FI_TAX_SCHEMAS_LIST, 
    FI_TAX_SCHEMA, 
    FI_CHART_OF_ACCOUNT_CREATE,
    FI_CHART_OF_ACCOUNT_EXISTS_CHECK, 
    FI_CHART_OF_ACCOUNTS_LIST, 
    FI_CHART_OF_ACCOUNT_RETRIEVE, 
    FI_CHART_OF_ACCOUNT_CHANGE, 
    FI_COMPANY_CREATE, 
    TIMEZONES_LIST, 
    TIMEZONES_BY_NAME, 
    FI_COMPANY_STATUS_LIST, 
    CO_COMPANY_LIST, 
    CO_COMPANY_BY_CODE, 
    FICO_RELATION_STATUS_LIST,
    CO_COST_VARIANT_LIST_RETRIEVE, 
    CO_COST_VARIANT_BY_CODE_RETRIEVE, 
    CO_COST_CENTER_PLAN_LIST, 
    CO_COST_CENTER_PLAN_BY_ID, 
    FICO_RELATION_TYPES, 
    FI_COMPANY_EXISTS, 
    FI_COMPANY_BY_LIST_RETRIEVE, 
    FI_COMPANY_BY_CODE_RETRIEVE, 
    FICO_RELATION_BY_ID_RETRIEVE, 
    FI_COMPANY_DOCUMENTS_RETRIEVE, 
    FI_COMPANY_MODIFY, 
    FI_ACCOUNTS_BY_CHART_OF_ACCOUNT_CODE
}
