/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.simplecore.erp.modules.logistics.plantmaintenance.workorders.utils;

/**
 *
 * @author user
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        OrdenTrabajo_Campos ordenTrabajo = new OrdenTrabajo_Campos();
        ordenTrabajo.setNUMERO_ORDEN("10003");
        ordenTrabajo.setID_ESTATUS("A");
        ordenTrabajo.setDESCRIPCION_ESTATUS("A-APROBADA");
        ordenTrabajo.setDESCRIPCION_GENERAL("REPARACION DE RETROEXCAVADORA 416E #4");
        ordenTrabajo.setTIPO_MTTO("Mecanico");
        ordenTrabajo.setCLASE_MTTO("Correctivo");
        ordenTrabajo.setCRITICIDAD("Alto");
        ordenTrabajo.setSISTEMA("Electrico");
        ordenTrabajo.setCOMPONENTE("Alternador");
        ordenTrabajo.setSINTOMA("No arranca");
        ordenTrabajo.setFECHA_INICIO("2024/06/27");
        ordenTrabajo.setFECHA_FIN("2024/06/27");
        ordenTrabajo.setFECHA_PROG("2024/06/27");
        ordenTrabajo.setFECHA_CIERRE("2024/06/27");
        ordenTrabajo.setFECHA_CREACION_ORDEN("2024/06/27");
        ordenTrabajo.setFECHA_AUTORIZADO("2024/06/27");
        ordenTrabajo.setCODIGO_EQUIPO("1046");
        ordenTrabajo.setDESCRIPCION_EQUIPO("RETRO EXCAVADORA 416E #4");
        ordenTrabajo.setCENTRO_COSTOS("100004");
        ordenTrabajo.setDESCRIPCION_CENTRO_COSTOS("GERENCIA DE MANTENIMIENTO");
        ordenTrabajo.setAREA("GM-3");
        ordenTrabajo.setDESCRIPCION_AREA("GERENCIA DE MANTENIENTO");
        ordenTrabajo.setUBICACION("PM01-PM1");
        ordenTrabajo.setDESCRIPCION_UBICACION("PLANTA CENTRAL");
        ordenTrabajo.setTIEMPO_ESTIMADO("5.00");
        ordenTrabajo.setTIEMPO_REAL("6.00");
        ordenTrabajo.setCOSTO_ESTIMADO("1,245.00");
        ordenTrabajo.setCOSTO_REAL("1,750.00");
        ordenTrabajo.setORDEN_CREADA_POR("SYSTEM");
        ordenTrabajo.setORDEN_PLANEADA_POR("SYSTEM");
        ordenTrabajo.setORDEN_APROBADA_POR("SYSTEM");
        ordenTrabajo.setORDEN_EJECUTADA_POR("SYSTEM");
        ordenTrabajo.setTEXTO_EXTENDIDO(jTextArea1.getText());        
        ordenTrabajo.setVALOR_CONTADOR("1,250.00 (hrs)");
        ordenTrabajo.setHOJA_RUTA("HR001-1");
        ordenTrabajo.setPLAN_MTTO("10003");
        ordenTrabajo.setPUNTO_MEDIDA("2002");
        
        OrdenTrabajoDataSource fuenteDatos = new OrdenTrabajoDataSource(ordenTrabajo);

        JasperReport_Orden_Mantenimiento nuevoReporte = new JasperReport_Orden_Mantenimiento();
        nuevoReporte.cargarJasperReport_Orden_Mtto(fuenteDatos);

        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
