
package com.simplecore.erp.client.gui.workspace.modules.financial.controlling.company.auxiliar;

import com.simplecore.erp.client.gui.utils.countries.*;

/**
 * @author Michael F. Sánchez
 * @since 2024
 * @project Lyra Core+ ERP
 * @company SimpleCore Systems
 * @country Republic of Nicaragua   
 * 
 */
public enum CompanyFieldsName {

    CONTROLLING_COMPANY_INFO_WINDOW_TITLE("CONTROLLING.COMPANY.INFO.WINDOW.TITLE"),
    CONTROLLING_COMPANY_INFO_WINDOW_TITLE_PANE("CONTROLLING.COMPANY.INFO.WINDOW.TITLE.PANE"),
    
    CONTROLLING_COMPANY_ID("CONTROLLING.COMPANY.ID"),
    CONTROLLING_COMPANY_CODE("CONTROLLING.COMPANY.CODE"),
    CONTROLLING_COMPANY_NAME("CONTROLLING.COMPANY.NAME"),
    CONTROLLING_COMPANY_LEGAL_NAME("CONTROLLING.COMPANY.LEGAL.NAME"),
    CONTROLLING_COMPANY_COUNTRY_CODE("CONTROLLING.COMPANY.COUNTRY.CODE"),
    CONTROLLING_COMPANY_CURRENCY_CODE("CONTROLLING.COMPANY.CURRENCY.CODE"),
    CONTROLLING_COMPANY_LANGUAGE("CONTROLLING.COMPANY.LANGUAGE"),
    CONTROLLING_COMPANY_TIME_ZONE("CONTROLLING.COMPANY.TIMEZONE"),
    CONTROLLING_COMPANY_TYPE("CONTROLLING.COMPANY.TYPE"),
    CONTROLLING_COMPANY_VERSION_CONTROL("CONTROLLING.COMPANY.VERSION.CONTROL"),
    CONTROLLING_COMPANY_ASSIGNMENT_RULES("CONTROLLING.COMPANY.ASSIGNMENT.RULES"),
    CONTROLLING_COMPANY_VALID_FROM("CONTROLLING.COMPANY.VALID.FROM"),
    CONTROLLING_COMPANY_VALID_TO("CONTROLLING.COMPANY.VALID.TO"),
    CONTROLLING_COMPANY_STATUS("CONTROLLING.COMPANY.STATUS"),
    CONTROLLING_COMPANY_CREATED_BY("CONTROLLING.COMPANY.CREATED.BY"),
    CONTROLLING_COMPANY_CREATED_AT("CONTROLLING.COMPANY.CREATED.AT"),
    CONTROLLING_COMPANY_UPDATED_BY("CONTROLLING.COMPANY.UPDATED.BY"),
    CONTROLLING_COMPANY_UPDATED_AT("CONTROLLING.COMPANY.UPDATED.AT");
    
    private final String key;

    CompanyFieldsName(String key) {
        this.key = key;
    }

    public String getKey() {
        return key;
    }
}