@accentFocusColor = #f33
@component.focusWidth=1
//Tree.paintLines=true
Tree.hash=#afafaf
Tree.leftChildIndent=10
Tree.rightChildIndent=10
Tree.icon.collapsedColor=#afafaf
Tree.icon.expandedColor=#afafaf

Tree.selectionInactiveBackground=#fc6
Tree.selectionInactiveForeground=#8e8e8e

TabbedPane.selectedBackground = #0037a3
TabbedPane.selectedForeground = #f3f3f3

TabbedPane.tabHeight = 10

TabbedPane.underlineColor = #003fcd

TabbedPane.showTabSeparators = true
TabbedPane.tabSeparatorsFullHeight = true


ScrollBar.trackInsets = 2,4,2,4
ScrollBar.thumbInsets = 2,2,2,2
ScrollBar.track = #e0e0e0
ScrollBar.width = 16
ScrollBar.track=#fff
ScrollBar.showButtons=true
ScrollPane.smoothScrolling=true

TitlePane.font = Roboto Medium 15 bold

TitlePane.buttonSize = 30,30
TitlePane.closeHoverBackground = #ffdb56
TitlePane.closePressedBackground = #fc2f2f 

TitlePane.buttonHoverBackground = #ffdb56
TitlePane.buttonPressedBackground = #0097ee

MenuBar.font = Roboto Light 13 bold
MenuBar.heigth = 50


MenuItem.textAcceleratorGap=30


PopupMenu.background=#f2f2f2
PopupMenu.borderColor=#8ca8c0

TableHeader.separatorColor = #787878
TableHeader.hoverForeground = #4b4b4b
TableHeader.hoverBackground = #cad8ed
