
package com.simplecore.erp.config.database.tables;


public enum materiales {
    
CODIGO_MATERIAL,
DESCRIPCION_MATERIAL,
ID_TIPO_MATERIAL,
DESCRIPCION_TIPO_MATERIAL,
ID_CLASE_MATERIAL,
DESCRIPCION_CLASE_MATERIAL,
MARCA,
MODELO,
SERIE,
ID_ESTATUS_MATERIAL,
DESCRIPCION_ESTATUS,
ID_AREA_MATERIAL,
DESCRIPCION_AREA_MATERIAL,
FECHA_FAB

    
}
