package com.simplecore.erp.modules.logistics.plantmaintenance.workorders.legacy.orders.auxiliares;

import javax.swing.JTable;
import com.simplecore.erp.gui.components.tables.lastversion.LyraTableModel;

public class Lista_Ordenes_Model {

    public static void set(JTable tabla) {

        LyraTableModel modelo = new LyraTableModel();

        String[] columnasES = {"Orden",
            "Estatus",
            "Descripción estatus",
            "Parada",
            "Titulo",
            "Tipo",
            "Descripción tipo",
            "Clase",
            "Descripción clase",
            "Prioridad",
            "Descripción prioridad",
            "Código sistema",
            "Descripción del sistema",
            "Código componente",
            "Descripción componente",
            "Código síntoma",
            "Descripción del síntoma",
            "Equipo",
            "Denominación del equipo",
            "Ubicación",
            "Denominación de ubicación",
            "Fecha inicio real",
            "Fecha fin real",
            "Hora inicio real",
            "Hora fin real",
            "Total horas real",
            "Fecha inicio prog.",
            "Fecha fin prog.",
            "Hora inicio prog.",
            "Hora fin prog.",
            "Total horas prog.",
            "Fecha de creación",
            "Fecha de aprobación",
            "Hora de creación",
            "Hora de autorización",
            "Total tiempo aprobación",
            "Grupo planificador",
            "Denominación del grupo planificador",
            "Código solicitante",
            "Nombre del solicitante",
            "Código responsable",
            "Nombre del responsable",
            "Sociedad",
            "Denominación sociedad",
            "Área",
            "Denominación de área",
            "Emplazamiento",
            "Denominación de emplazamiento",
            "Centro Costos",
            "Denominación del centro de costos",
            "Orden creada por",
            "Orden planeada por",
            "Orden aprobada por",
            "Orden ejecutada por",
            "Tiempo estimado",
            "Tiempo real",
            "Costo estimado",
            "Costo real",
            "Contador",
            "Valor contador",
            "Hoja ruta",
            "Plan de mtto",};
        String[] columnasEN = {"Order",
            "Status",
            "Status description",
            "Stop",
            "Title",
            "Type",
            "Type description",
            "Class",
            "Class description",
            "Priority",
            "Priority description",
            "System code",
            "System description",
            "Component code",
            "Component description",
            "Symptom code",
            "Symptom description",
            "Equipment",
            "Equipment name",
            "Location",
            "Location name",
            "Actual start date",
            "Actual end date",
            "Actual start time",
            "Actual end time",
            "Actual total hours",
            "Prog. start date",
            "Prog. end date",
            "Prog. start time",
            "Prog. end time",
            "Prog. total hours",
            "Creation date",
            "Approval date",
            "Creation time",
            "Authorization time",
            "Total approval time",
            "Planning group",
            "Planning group name",
            "Requestor code",
            "Requestor name",
            "Responsible code",
            "Responsible name",
            "Company name",
            "Company name",
            "Area",
            "Area name",
            "Emplacement",
            "Emplacement name",
            "Cost center",
            "Cost center name",
            "Order created by",
            "Order planned by",
            "Order approved by",
            "Order executed by",
            "Estimated time",
            "Actual time",
            "Estimated cost",
            "Actual cost",
            "Accountant",
            "Accountant value",
            "Route sheet",
            "Maintenance plan",};
        String[] columnasFR = {"Ordre",
            "Statut",
            "Description du statut",
            "Arrêt",
            "Qualification",
            "Gars",
            "Description du type",
            "Classe",
            "Description du cours",
            "Priorité",
            "Description priorité",
            "Code système",
            "Description du système",
            "Code composant",
            "Description du composant",
            "Code symptôme",
            "Description des symptômes",
            "Équipement",
            "Nom de l'équipement",
            "Emplacement",
            "Désignation du lieu",
            "Date de début réelle",
            "Date de fin réelle",
            "Heure de début réelle",
            "Heure de fin réelle",
            "Total des heures réelles",
            "Date de début du planning",
            "Date de fin du programme",
            "Heure de début du programme",
            "Heure de fin du programme",
            "Total des heures programmées",
            "Date de création",
            "Date d'approbation",
            "Temps de création",
            "Délai d'autorisation",
            "Délai total d'approbation",
            "Groupe de planification",
            "Nom du groupe de planification",
            "Demande de code",
            "Nom du demandeur",
            "Code responsable",
            "Nom de la personne responsable",
            "Société",
            "Nom de l'entreprise",
            "Zone",
            "Désignation de la zone",
            "Emplacement",
            "Nom de l'emplacement",
            "Centre de coûts",
            "Nom du centre de coûts",
            "Ordre créée par",
            "Ordre planifiée par",
            "Ordre approuvée par",
            "Ordre exécuté par",
            "Temps estimé",
            "Temps réel",
            "Coût estimé",
            "Coût réel",
            "Comptoir",
            "Valeur du compteur",
            "Feuille de route",
            "Plan Mtto",};
        String[] columnasPT = {"Ordem",
            "Status",
            "Descrição do status",
            "Parar",
            "Título",
            "Tipo",
            "Descrição do tipo",
            "Classe",
            "Descrição da classe",
            "Prioridade",
            "Prioridade da descrição",
            "Código do sistema",
            "Descrição do sistema",
            "Código do componente",
            "Descrição do Componente",
            "Código do sintoma",
            "Descrição do sintoma",
            "Equipamento",
            "Nome do equipamento",
            "Localização",
            "Designação de localização",
            "Data de início real",
            "Data de término real",
            "Hora de início real",
            "Hora de término real",
            "Total de horas reais",
            "Data de início do agendamento",
            "Data de término do programa",
            "Hora de início do programa",
            "Hora de término do programa",
            "Total de horas programadas",
            "Data de criação",
            "Data de aprovação",
            "Hora de criação",
            "Tempo de autorização",
            "Tempo total de aprovação",
            "Grupo de planejamento",
            "Nome do grupo de planejamento",
            "Solicitando código",
            "Nome do requerente",
            "Código responsável",
            "Nome do responsável",
            "Sociedade",
            "Nome da empresa",
            "Área",
            "Designação de área",
            "Emplacamento",
            "Nome do emplacamento",
            "Centro de Custo",
            "Nome do centro de custo",
            "Pedido criado por",
            "Pedido planejado por",
            "Pedido aprovado por",
            "Ordem executada por",
            "Tempo estimado",
            "Tempo real",
            "Custo estimado",
            "Custo real",
            "Contador",
            "Valor do contador",
            "Folha de rota",
            "Plano Mtto",};

            modelo.setColumnIdentifiers(columnasEN);
            tabla.setModel(modelo);
        
    }
}
