
package com.simplecore.erp.client.models.maintree;

/**
 * @author Michael F. Sánchez
 * @since 2024
 * @project Lyra Core+ ERP
 * @company SimpleCore Systems
 * @country Republic of Nicaragua   
 * 
 */
public enum BusinessTransactions {
//    FI("FI"), //	Financial Accounting	(Contabilidad Financiera	)
//    FI_ENT("FI-ENT"), //FI Companies	(Sociedades FI	)
    EN01("EN01"), //	Create Financial Company(Creación de sociedad financiera	)
    EN02("EN02"), //	Modify Financial Company(Modificación de sociedad financiera	)
    EN03("EN03"), //	View Financial Company	(Visualización de sociedad financiera	)
    EN04("EN04"), //	View Company List	(Visualización de la lista de sociedades	)
//    FI_COA("FI-COA"), //	Chart of Accounts(Plan de Cuentas	)
    CO01("CO01"), //	Create Chart of Accounts(Creación de plan de cuentas	)
    CO02("CO02"), //	Modify Chart of Accounts(Modificación de plan de cuentas	)
    CO03("CO03"), //	View Chart of Accounts(Visualización de plan de cuentas	)
    CO04("CO04"), //	Assign Accounts	(Asignación de cuentas	)
    CO05("CO05"), //	Chart of Accounts List(Lista de planes de cuentas	)
//    FI_ACC("FI-ACC"), //	Accounts	(	Cuentas	)
    AC11("AC11"), //	Account Classes	(	Clases de cuentas	)
    AC12("AC12"), //	Account Types	(	Tipos de cuentas	)
    AC13("AC13"), //	Accounting Classification Definition	(	Definición de clasificación contable	)
    AC14("AC14"), //	Account Range Assignment by Class	(	Asignación de rangos de cuentas por clase	)
    AC15("AC15"), //	Create Accounting Account	(	Creación de cuenta contable	)
    AC16("AC16"), //	Modify Accounting Account	(	Modificación de cuenta contable	)
    AC17("AC17"), //	View Accounting Account	(	Visualización de cuenta contable	)
    AC18("AC18"), //	Accounting Account List	(	Lista de cuentas contables	)
//    FI_RUL("FI-RUL"), //	Accounting Rules	(	Reglas Contables	)
    RU01("RU01"), //	Create Accounting Rule	(	Creación de regla contable	)
    RU02("RU02"), //	Modify Accounting Rule	(	Modificación de regla contable	)
    RU03("RU03"), //	View Accounting Rule	(	Visualización de regla contable	)
    RU04("RU04"), //	Accounting Rules List	(	Lista de reglas contables	)
//    FI_BOK("FI-BOK"), //	Accounting Books	(	Libros Contables	)
//    FI_BOK_JRN("FI-BOK-JRN"), //	Journal Book	(	Libro Diario	)
    JR01("JR01"), //	Create Journal Book	(	Creación de libro diario	)
    JR02("JR02"), //	Modify Journal Book	(	Modificación de libro diario	)
    JR03("JR03"), //	Assign to General Ledger	(	Asignación a libro mayor	)
    JR04("JR04"), //	View Journal Book	(	Visualización de libro diario	)
    JR05("JR05"), //	View Journal Books List	(	Visualización de la lista de libros diarios	)
//    FI_BOK_GL("FI-BOK-GL"), //	General Ledger	(	Libro Mayor	)
    GL01("GL01"), //	Create General Ledger	(	Creación de libro mayor	)
    GL02("GL02"), //	Modify General Ledger	(	Modificación de libro mayor	)
    GL03("GL03"), //	View General Ledger	(	Visualización de libro mayor	)
    GL04("GL04"), //	View General Ledger List	(	Visualización de la lista de libros mayores	)
    GL05("GL05"), //	Create New Fiscal Year	(	Creación de nuevo ejercicio	)
//    FI_FRT("FI-FRT"), //	Financial Reports	(	Reportes Contables	)
//    FI_FRT_IST("FI-FRT-IST"), //	Income Statement	(	Estado de Resultados	)
    ST01("ST01"), //	Create Income Statement	(	Creación de estado de resultados	)
    ST02("ST02"), //	Modify Income Statement	(	Modificación de estado de resultados	)
    ST03("ST03"), //	Assign to General Ledger	(	Asignación a libro mayor	)
    ST04("ST04"), //	View Income Statement	(	Visualización de estado de resultados	)
//    FI_FRT_BSH("FI-FRT-BSH"), //	Balance Sheet	(	Balance General	)
    BS01("BS01"), //	Create Balance Sheet	(	Creación de balance general	)
    BS02("BS02"), //	Modify Balance Sheet	(	Modificación de balance general	)
    BS03("BS03"), //	Assign to General Ledger	(	Asignación a libro mayor	)
    BS04("BS04"), //	View Balance Sheet	(	Visualización de balance general	)
    BS05("BS05"), //	View Balance Sheets List	(	Visualización de la lista de balances generales	)
//    FI_FRT_CFS("FI-FRT-CFS"), //	Cash Flow Statement	(	Flujo de Caja	)
    CF01("CF01"), //	Create Cash Flow Statement	(	Creación de flujo de caja	)
    CF02("CF02"), //	Modify Cash Flow Statement	(	Modificación de flujo de caja	)
    CF03("CF03"), //	Assign to General Ledger	(	Asignación a libro mayor	)
    CF04("CF04"), //	View Cash Flow Statement	(	Visualización de flujo de caja	)
    CF05("CF05"), //	View Cash Flow Statements List	(	Visualización de la lista de flujos de caja	)
//    FI_SMG("FI-SMG"), //	Supplier Management	(	Gestión con Proveedores	)
    SM01("SM01"), //	Create Supplier Invoice	(	Crear factura de proveedor	)
    SM02("SM02"), //	Approve and Process Payments	(	Aprobar y procesar pagos	)
    SM03("SM03"), //	Payment Reconciliation	(	Conciliación de pagos	)
    SM04("SM04"), //	Accounts Payable Report	(	Reporte de cuentas por pagar	)
    SM05("SM05"), //	Credit/Debit Notes	(	Notas de crédito/débito	)
//    FI_CMG("FI-CMG"), //	Customer Management	(	Gestión con Clientes	)
    CM01("CM01"), //	Accounts Receivable (AR)	(	Cuentas por Cobrar (AR)	)
    CM02("CM02"), //	Create Customer Invoice	(	Crear factura de cliente	)
    CM03("CM03"), //	Modify Customer Invoice	(	Modificación de factura de cliente	)
    CM04("CM04"), //	View Customer Invoice	(	Visualización de factura de cliente	)
    CM05("CM05"), //	Customer Invoices List	(	Lista de facturas de clientes	)
    CM06("CM06"), //	Register and Reconcile Payments	(	Registrar y conciliar pagos	)
    CM07("CM07"), //	Generate Account Statement	(	Generar estado de cuenta	)
    CM08("CM08"), //	Outstanding Revenue Report	(	Reporte de ingresos pendientes	)
    CM09("CM09"), //	Collection Management	(	Gestión de cobros	)
//    FI_FAM("FI-FAM"), //	Fixed Asset Management	(	Gestión de Activos Fijos	)
    FA01("FA01"), //	Register Fixed Asset	(	Registrar activo fijo	)
    FA02("FA02"), //	Modify Asset Data	(	Modificar datos de activo	)
    FA03("FA03"), //	Depreciation Calculation and Application	(	Cálculo y aplicación de depreciación	)
    FA04("FA04"), //	Asset Disposal or Sale	(	Baja o venta de activo fijo	)
    FA05("FA05"), //	Fixed Asset Reports	(	Reportes de activos fijos	)
//    FI_TAX("FI-TAX"), //	Taxes and Compliance	(	Impuestos y Cumplimiento	)
    TX01("TX01"), //	Create Tax	(	Creación de impuesto	)
    TX02("TX02"), //	Modify Tax	(	Modificación de impuesto	)
    TX03("TX03"), //	Tax List	(	Lista de impuestos	)
    TX04("TX04"), //	Tax Calculation (VAT, Income Tax, etc.)	(	Cálculo de impuestos (IVA, ISR, etc.)	)
    TX05("TX05"), //	Tax Declaration	(	Declaración de impuestos	)
    TX06("TX06"), //	Retention Generation	(	Generación de retenciones	)
    TX07("TX07"), //	Payment of Tax Obligations	(	Pago de obligaciones fiscales	)
//    FI_TBM("FI-TBM"), //	Treasury and Banking Management	(	Tesorería y Gestión Bancaria	)
    BK01("BK01"), //	Bank Reconciliation	(	Conciliación bancaria	)
    BK02("BK02"), //	Bank Account Management	(	Gestión de cuentas bancarias	)
    BK03("BK03"), //	Cash Flow and Financial Projection	(	Flujo de caja y proyección financiera	)
    BK04("BK04"), //	Bank Transfers and Payments	(	Transferencias y pagos bancarios	)

//    CO("CO"), //	Controlling	(	Controlling	)
//    CO_ENT("CO-ENT"), //	CO Companies	(	Sociedades CO	)
    CE01("CE01"), //	Create CO Company	(	Creación de sociedad CO	)
    CE02("CE02"), //	Modify CO Company	(	Modificación de sociedad CO	)
    CE03("CE03"), //	View CO Company	(	Visualización de sociedad CO	)
    CE04("CE04"), //	CO Companies List	(	Lista de sociedades CO	)
//    CO_CCT("CO-CCT"), //	Cost Centers	(	Centros de Costos	)
    CC01("CC01"), //	Create Cost Center	(	Creación de centro de costos	)
    CC02("CC02"), //	Modify Cost Center	(	Modificación de centro de costos	)
    CC03("CC03"), //	View Cost Center	(	Visualización de centro de costos	)
    CC04("CC04"), //	Cost Centers List	(	Lista de centros de costos	)
//    CO_CDT("CO-CDT"), //	Cost Distribution	(	Distribución de Costos	)
    AC01("AC01"), //	Account Assignment	(	Asignación de cuentas	)
    AC02("AC02"), //	Cost Reports and Analysis	(	Reportes de costos y análisis	)
//    CO_COR("CO-COR"), //	Cost Orders	(	Órdenes de Costos	)
    OR01("OR01"), //	Create Cost Order	(	Creación de orden de costos	)
    OR02("OR02"), //	Modify Cost Order	(	Modificación de orden de costos	)
    OR03("OR03"), //	View Cost Order	(	Visualización de orden de costos	)
    OR04("OR04"), //	Cost Orders List	(	Lista de órdenes de costos	)
//    CO_PAC("CO-PAC"), //	Profitability Accounting	(	Contabilidad de Beneficios	)
    PC01("PC01"), //	Define Profit Centers	(	Definir centros de beneficio	)
    PC02("PC02"), //	Profitability Tracking	(	Seguimiento de rentabilidad	)
    PC03("PC03"), //	Profit Report by Area	(	Reporte de beneficios por área	)
    PC04("PC04"), //	Product Costing (PC)	(	Cálculo de Costos de Producto (PC)	)
    PC05("PC05"), //	Define Cost Components	(	Definir componentes de costos	)
    PC06("PC06"), //	Cost Estimation	(	Estimación de costos	)
    PC07("PC07"), //	Variance Analysis	(	Análisis de variaciones	)
//    LO("LO"), //	Logistic	(	Logística	)
//    SD("SD"), //	Sales and Distribution	(	Ventas y Distribución	)
//    SD_CMG("SD-CMG"), //	Customer Management	(	Gestión de Clientes	)
    CS01("CS01"), //	Create Customer	(	Crear cliente	)
    CS02("CS02"), //	Modify Customer	(	Modificar cliente	)
    CS03("CS03"), //	View Customer	(	Visualizar cliente	)
    CS04("CS04"), //	Customers List	(	Lista de clientes	)
//    SD_COR("SD-COR"), //	Customer Orders	(	Pedidos de Clientes	)
    COR1("COR1"), //	Create Customer Order	(	Crear pedido de cliente	)
    COR2("COR2"), //	Modify Order	(	Modificación de pedido	)
    COR3("COR3"), //	Orders List	(	Lista de pedidos	)
    COR4("COR4"), //	Customer Analysis	(	Análisis de clientes	)
    COR5("COR5"), //	Delivery Confirmation	(	Confirmación de entrega	)
    COR6("COR6"), //	Billing and Order Closure	(	Facturación y cierre de pedido	)
    COR7("COR7"), //	Sales and Discounts Report	(	Reporte de ventas y descuentos	)
//    SD_PDS("SD-PDS"), //	Pricing & Discounts	(	Precios y Descuentos	)
    DP01("DP01"), //	Define Price Lists	(	Definir listas de precios	)
    DP02("DP02"), //	Apply Discounts	(	Aplicar descuentos	)
//    PM("PM"), //	Procurement Management	(	Gestión de Compras	)
//    PM_PRQ("PM-PRQ"), //	Purchase Requests	(	Solicitudes de Compra	)
    PR01("PR01"), //	Create Purchase Request	(	Crear solicitud de compra	)
    PR02("PR02"), //	Modify Purchase Request	(	Modificar solicitud de compra	)
    PR03("PR03"), //	View Purchase Request	(	Visualizar solicitud de compra	)
    PR04("PR04"), //	Purchase Request List	(	Lista de solicitudes de compra	)
//    PM_POR("PM-POR"), //	Purchase Orders	(	Órdenes de Compra	)
    PO01("PO01"), //	Create Purchase Order	(	Crear orden de compra	)
    PO02("PO02"), //	Modify Purchase Order	(	Modificar orden de compra	)
    PO03("PO03"), //	View Purchase Order	(	Visualizar orden de compra	)
    PO04("PO04"), //	Purchase Order List	(	Lista de órdenes de compra	)
//    PM_SUP("PM-SUP"), //	Suppliers	(	Proveedores	)
    SUP1("SUP1"), //	Create Supplier	(	Crear proveedor	)
    SUP2("SUP2"), //	Modify Supplier	(	Modificar proveedor	)
    SUP3("SUP3"), //	View Supplier	(	Visualizar proveedor	)
    SUP4("SUP4"), //	Supplier List	(	Lista de proveedores	)
//    WM("WM"), //	Warehouse Management	(	Administración de Almacenes	)
//    WM_WMT("WM-WMT"), //	Materials	(	Materiales	)
    WM01("WM01"), //	Create Material	(	Crear Material	)
    WM02("WM02"), //	Edit Material	(	Modificar Material	)
    WM03("WM03"), //	View Material	(	Visualizar Material	)
    WM04("WM04"), //	Materials List	(	Lista de Materiales	)
//    WM_WHS("WM-WHS"), //	Warehouse	(	Almacenes	)
    WH01("WH01"), //	Create Warehouse	(	Crear Almacén	)
    WH02("WH02"), //	Modify Warehouse	(	Modificar Almacén	)
    WH03("WH03"), //	View Warehouse	(	Visualizar Almacén	)
    WH04("WH04"), //	Warehouse List	(	Lista de Almacenes	)
//    WM_INV("WM-INV"), //	Inventory and Warehouses	(	Inventario y Almacenes	)
    MI01("MI01"), //	Material Inbound and Outbound	(	Entrada y salida de materiales	)
    MI02("MI02"), //	Material Requisition	(	Requisición de material	)
    MI03("MI03"), //	Inventory Adjustments	(	Ajustes de inventario	)
    MI04("MI04"), //	Stock and Turnover Report	(	Reporte de stock y rotación	)
//    LMG("LMG"), //	Logistics Management  	(	Logistics Management  	)
//    LMG_LCT("LMG-LCT"), //	Logistics Centers	(	Centros Logisticos	)
    LC01("LC01"), //	Create Logistics Center	(	Crear centro logistico	)
    LC02("LC02"), //	Edit Logistics Center	(	Modificar centro logistico	)
    LC03("LC03"), //	View Logistics Center	(	Visualizar centro logistico	)
    LC04("LC04"), //	Logistics Centers List	(	Lista de centros logisticos	)
//    LMG_LSC("LMG-LSC"), //	Site Centers	(	Centro de Emplazamiento	)
    SC01("SC01"), //	Create Site Center	(	Crear Centro de Emplazamiento	)
    SC02("SC02"), //	Edit Site Center	(	Modificar Centro de Emplazamiento	)
    SC03("SC03"), //	View Site Center	(	Visualizar Centro de Emplazamiento	)
    SC04("SC04"), //	Site Centers List	(	Lista de Centro de Emplazamiento	)
//    LMG_LPC("LMG-LPC"), //	Planning Centers	(	Centro de planificacion	)
    PC11("PC11"), //	Create Planning Center	(	Crear Centro de planificacion	)
    PC12("PC12"), //	Edit Planning Center	(	Modificar Centro de Planificacion	)
    PC13("PC13"), //	View Planning Center	(	Visualizar Centro de Planificacion	)
    PC14("PC14"), //	Planning Centers List	(	Lista de Centros de planificacion	)
//    LMG_LAR("LMG-LAR"), //	Areas	(	Areas	)
    CA01("CA01"), //	Create Company Area	(	Crear Area de Empresa	)
    CA02("CA02"), //	Edit Company Area	(	Modificar Area de Empresa	)
    CA03("CA03"), //	View Company Area	(	Visualizar Area de Empresa	)
    CA04("CA04"), //	Company Areas List	(	Lista Area de Empresa	)
//    LMG_LST("LMG-LST"), //	Sites	(	Emplazamientos	)
    ST11("ST11"), //	Create Site	(	Crear Emplazamiento	)
    ST12("ST12"), //	Edit Site	(	Modificar Emplazamiento	)
    ST13("ST13"), //	View Site	(	Visualizar Emplazamiento	)
    ST14("ST14"), //	Sites List	(	Lista de Emplazamientos	)
//    LMG_LPG("LMG-LPG"), //	Planning Groups	(	Grupos Planificadores	)
    PG01("PG01"), //	Create Planning Group	(	Crear Grupo Planificador	)
    PG02("PG02"), //	Edit Planning Group	(	Modificar Grupo Planificador	)
    PG03("PG03"), //	View Planning Group	(	Visualizar Grupo Planificador	)
    PG04("PG04"), //	Planning Groups List	(	Lista de Grupos Planificadores	)
//    PPM("PPM"), //	Production and Maintenance	(	Producción y Mantenimiento	)
//    PPM_PP("PPM-PP"), //	Production Planning	(	Planificación de Producción	)
    PP01("PP01"), //	Create Production Plans	(	Creación de planes de producción	)
    PP02("PP02"), //	Generate Production Orders	(	Generación de órdenes de producción	)
    PP03("PP03"), //	Production Tracking	(	Seguimiento de producción	)
//    PPM_OS("PPM-OS"), //	Work Orders & Scheduling	(	Órdenes de Trabajo y Programación	)
    PP04("PP04"), //	Create Work Order	(	Crear orden de trabajo	)
    PP05("PP05"), //	Assign Tasks	(	Asignar tareas	)
    PP06("PP06"), //	Progress Tracking	(	Seguimiento de progreso	)
//    PPM_MM("PPM-MM"), //	Maintenance Management	(	Gestión del Mantenimiento	)
//    PPM_MM_ASM("PPM-MM-ASM"), //	Asset Management	(	Gestión de Activos	)
    ME01("ME01"), //	Create Equipment	(	Creación de equipo	)
    ME02("ME02"), //	Modify Equipment	(	Modificación de equipo	)
    ME03("ME03"), //	View Equipment	(	Visualización de equipo	)
    ME04("ME04"), //	Equipment List	(	Lista de equipos	)
//    PPM_MM_TLC("PPM-MM-TLC"), //	Technical Locations	(	Ubicaciones Técnicas	)
    ML01("ML01"), //	Create Technical Location	(	Crear ubicación técnica	)
    ML02("ML02"), //	Modify Technical Location	(	Modificar ubicación técnica	)
    ML03("ML03"), //	View Technical Location	(	Visualización de ubicación técnica	)
//    PPM_MM_MNT("PPM-MM-MNT"), //	Maintenance Notifications	(	Avisos	)
    MN01("MN01"), //	Create Maintenance Notification	(	Crear aviso de mantenimiento	)
    MN02("MN02"), //	Modify Notification	(	Modificar aviso	)
    MN03("MN03"), //	View Notification	(	Visualizar aviso	)
    MN04("MN04"), //	Notification List	(	Lista de avisos	)
//    PPM_MM_MWO("PPM-MM-MWO"), //	Work Orders	(	Órdenes	)
    MO01("MO01"), //	Create Work Order	(	Crear orden de trabajo	)
    MO02("MO02"), //	Modify Work Order	(	Modificar orden de trabajo	)
    MO03("MO03"), //	View Work Order	(	Visualizar orden de trabajo	)
    MO04("MO04"), //	Work Order List	(	Lista de órdenes de trabajo	)
    MO05("MO05"), //	Order Settlement	(	Liquidación de órdenes	)
//    PPM_MM_TSK("PPM-MM-TSK"), //	Task Lists	(	Hojas de Rutina	)
    MT01("MT01"), //	Create Task List	(	Crear hoja de rutina	)
    MT02("MT02"), //	Modify Task List	(	Modificar hoja de rutina	)
    MT03("MT03"), //	View Task List	(	Visualizar hoja de rutina	)
//    PPM_MM_MPL("PPM-MM-MPL"), //	Maintenance Plans	(	Plan de Mantenimiento	)
    MP01("MP01"), //	Create Maintenance Plan	(	Crear plan de mantenimiento	)
    MP02("MP02"), //	Modify Maintenance Plan	(	Modificar plan de mantenimiento	)
    MP03("MP03"), //	View Maintenance Plan	(	Visualizar plan de mantenimiento	)
    MP04("MP04"), //	Schedule Maintenance Plan	(	Programar plan de mantenimiento	)
//    PPM_MM_MMT("PPM-MM-MMT"), //	Maintenance Meters	(	Medidores de Mantenimiento	)
    MM01("MM01"), //	Create Meter	(	Crear medidor	)
    MM02("MM02"), //	Modify Meter	(	Modificar medidor	)
    MM03("MM03"), //	View Meter	(	Visualizar medidor	)
    MM04("MM04"), //	Create Measurement Report	(	Crear reporte de medición	)
    MM05("MM05"), //	Modify Measurement Report	(	Modificar reporte de medición	)
//    QC("QC"), //	Quality & Compliance	(	Calidad y Cumplimiento (QC)	)
//    QC_MNG("QC-MNG"), //	Quality Management	(	Gestión de Calidad	)
    QC01("QC01"), //	Define Quality Standards	(	Definir estándares de calidad	)
    QC02("QC02"), //	Perform Quality Inspections	(	Realizar inspecciones de calidad	)
    QC03("QC03"), //	Generate Quality Reports	(	Generar reportes de calidad	)
//    HR("HR"), //	Human Resources	(	Recursos Humanos (HR)	)
//    HR_PMG("HR-PMG"), //	Personnel Management	(	Gestión de Personal	)
    HR01("HR01"), //	Employee Registration and Modification	(	Registro y modificación de empleados	)
    HR02("HR02"), //	Attendance and Schedule Control	(	Control de asistencias y horarios	)
    HR03("HR03"), //	Performance Evaluations	(	Evaluaciones de desempeño	)
//    HR_PBF("HR-PBF"), //	Payroll and Benefits	(	Nómina y Beneficios	)
    HR04("HR04"), //	Payroll Calculation	(	Cálculo de nómina	)
    HR05("HR05"), //	Salary and Bonus Payments	(	Pago de salarios y bonos	)
    HR06("HR06"), //	Labor Cost Reports	(	Reporte de costos laborales	)
//    BI("BI"), //	Business Intelligence	(	Inteligencia de Negocios	)
//    BI_RAN("BI-RAN"), //	Reports and Analysis	(	Reportes y Análisis	)
    BI01("BI01"), //	Finance: Cash Flow and Profitability Reports	(	Finanzas: Reportes de flujo de caja y rentabilidad	)
    BI02("BI02"), //	Sales: Customer and Product Analysis	(	Ventas: Análisis de clientes y productos	)
    BI03("BI03"), //	Production: Cost and Efficiency Reports	(	Producción: Reportes de costos y eficiencia	)
    BI04("BI04"), //	Personnel: Payroll and Shift Analysis	(	Personal: Análisis de nómina y turnos	)
//    SYS("SYS"), //	System Security and Administration	(	Seguridad y Administración del Sistema	)
//    SYS_USP("SYS-USP"), //	Users and Permissions	(	Usuarios y Permisos	)
    SYS_1("SYS_1"), //	User Creation and Management	(	Creación y gestión de usuarios	)
    SYS_2("SYS_2"), //	Role and Permission Definition	(	Definición de roles y permisos	)
    SYS_3("SYS_3"), //	Security Audit	(	Auditoría de seguridad	)
//    SYS_CFG("SYS-CFG"), //	System Configuration	(	Configuración del Sistema	)
    SYS_4("SYS_4"), //	General Parameters and Customization	(	Parámetros generales y personalización	)
    SYS_5("SYS_5"), //	Data Backup and Restoration	(	Respaldo y restauración de datos	)
    SYS_6("SYS_6");	//	System Monitoring and Logs	(	Monitoreo del sistema y registros	)

    private final String key;

    private BusinessTransactions(String key) {
        this.key = key;
    }

    public String getKey() {
        return key;
    }
}
