package com.simplecore.erp.modules.logistics.plantmaintenance.equipment.legacy.utils;

import javax.swing.JTable;
import com.simplecore.erp.gui.components.tables.lastversion.LyraTableModel;

public class Modelo_Lista_Equipos_Todos_Los_Campos {

    public static void set(JTable tabla) {

        LyraTableModel modelo = new LyraTableModel();

        String[] columnasES = {"Equipo",
                                "Denominación",
                                "Estatus",
                                "Descripción estatus",
                                "Tipo",
                                "Descripción tipo",
                                "Prioridad",
                                "Descripción prioridad",
                                "Marca",
                                "Modelo",
                                "Serie",
                                "Fecha fabricación",
                                "Dimensiones",
                                "Fecha Psta. Serv.",
                                "Valor Adquisición",
                                "Moneda",
                                "Fecha Adquisición",
                                "Fabricante",
                                "Tipo",
                                "Núm.. Parte",
                                "Serie",
                                "País construcción",
                                "Año construcción",
                                "Mes construcción",
                                "Sociedad",
                                "Activo fijo",
                                "Centro coste",
                                "Descripción centro coste",
                                "Emplazamiento",
                                "Denominación emplazamiento",
                                "Área",
                                "Descripción área",
                                "Equipo superior",
                                "Denominación equipo superior",
                                "Ubicación",
                                "Denominación ubicación",
                                "Potencia mecánica",
                                "R.P.M",
                                "Torque",
                                "Capacidad máx.. mecánica",
                                "Capacidad min. mecánica",
                                "Tipo energía mecánica",
                                "Flujo",
                                "Ratio mecánico",
                                "Frecuencia mecánica",
                                "Lubricante",
                                "Rodamientos",
                                "Voltaje",
                                "Frecuencia eléctrica",
                                "Potencia eléctrica",
                                "Capacidad máx.. eléctrica",
                                "Capacidad min. eléctrica",
                                "Tipo energía eléctrica",
                                "Eficiencia nominal",
                                "Eficiencia mínima",
                                "Factor potencia",
                                "Factor servicio",
                                "Ratio eléctrico",
                                "Fases",
                                "% Elev. Temp.",
                                "Volumen",
                                "Armazón",
                                "Núm. Catalogo",
                                "Núm. Especificación",
                                "Serial",
                                "Peso",
                                "Clase",
                                "Estilo",
                                "Diseño",
                                "Vibración",
                                "Plano 1",
                                "Plano 2",
                                "Plano 3",
                                "Creado por",
                                "Modificado por",
                                "Fecha creación",
                                "Fecha modificación",};

        String[] columnasEN = {"Equipment",
                                "Name",
                                "Status",
                                "Status description",
                                "Type",
                                "Type description",
                                "Priority",
                                "Priority description",
                                "Brand",
                                "Model",
                                "Series",
                                "Manufacturing date",
                                "Dimensions",
                                "Service pack date",
                                "Purchase value",
                                "Currency",
                                "Purchase date",
                                "Manufacturer",
                                "Type",
                                "Part no.",
                                "Series",
                                "Construction country",
                                "Construction year",
                                "Construction month",
                                "Company",
                                "Fixed asset",
                                "Cost center",
                                "Cost center description",
                                "Location",
                                "Site name",
                                "Area",
                                "Area description",
                                "Superior equipment",
                                "Superior equipment name",
                                "Location",
                                "Location name",
                                "Power mechanical",
                                "R.P.M",
                                "Torque",
                                "Max. mechanical capacity",
                                "Min. mechanical capacity",
                                "Mechanical power type",
                                "Flow",
                                "Mechanical ratio",
                                "Mechanical frequency",
                                "Lubricant",
                                "Bearings",
                                "Voltage",
                                "Electrical frequency",
                                "Electrical power",
                                "Max. electrical capacity",
                                "Min. electrical capacity",
                                "Electrical power type",
                                "Nominal efficiency",
                                "Minimum efficiency",
                                "Power factor",
                                "Service factor",
                                "Electrical ratio",
                                "Phases",
                                "% Elev. Temp.",
                                "Volume",
                                "Frame",
                                "Catalog No.",
                                "No. Specification",
                                "Serial",
                                "Weight",
                                "Class",
                                "Style",
                                "Design",
                                "Vibration",
                                "Plane 1",
                                "Plane 2",
                                "Plane 3",
                                "Created by",
                                "Modified by",
                                "Creation date",
                                "Modification date"};

        String[] columnasFR = {"Équipement",
                                "Dénomination",
                                "Statut",
                                "Description de l'état",
                                "Gars",
                                "Description du type",
                                "Priorité",
                                "Description de la priorité",
                                "Marque",
                                "Modèle",
                                "Série",
                                "Date de fabrication",
                                "Dimensions",
                                "Date de service",
                                "Valeur d'acquisition",
                                "Devise",
                                "Date d'acquisition",
                                "Fabricant",
                                "Gars",
                                "Numéro de pièce.",
                                "Série",
                                "Construction de campagne",
                                "Année de construction",
                                "Mois de la construction",
                                "Société",
                                "Immobilisations",
                                "Centre de coûts",
                                "Description du centre de coûts",
                                "Site",
                                "Nom du lieu",
                                "Zone",
                                "Description de la zone",
                                "Meilleure équipe",
                                "Désignation d'équipement supérieur",
                                "Emplacement",
                                "Nom du lieu",
                                "Puissance mécanique",
                                "R.P.M",
                                "Couple",
                                "Capacité mécanique max.",
                                "Capacité mécanique min.",
                                "Type d'énergie mécanique",
                                "Couler",
                                "Rapport mécanique",
                                "Fréquence mécanique",
                                "Lubrifiant",
                                "Roulements",
                                "Tension",
                                "Fréquence électrique",
                                "Énergie électrique",
                                "Capacité électrique max.",
                                "Capacité électrique min.",
                                "Type d'énergie électrique",
                                "Efficacité nominale",
                                "Efficacité minimale",
                                "Facteur de puissance",
                                "Facteur de service",
                                "Rapport électrique",
                                "Phases",
                                "% Temp. Élévation",
                                "Volume",
                                "Cadre",
                                "N° de catalogue.",
                                "N° de spécification.",
                                "En série",
                                "Poids",
                                "Classe",
                                "Style",
                                "Conception",
                                "Vibration",
                                "Avion 1",
                                "Avion 2",
                                "Avion 3",
                                "Créé par",
                                "Modifié par",
                                "Date de création",
                                "Date de modification"};

        String[] columnasPT = {"Equipamento",
                                "Denominação",
                                "Status",
                                "Descrição do estado",
                                "Cara",
                                "Descrição do tipo",
                                "Prioridade",
                                "Descrição da prioridade",
                                "Marca",
                                "Modelo",
                                "Série",
                                "Data de fabricação",
                                "Dimensões",
                                "Data de entrega",
                                "Valor de Aquisição",
                                "Moeda",
                                "Data de Aquisição",
                                "Fabricante",
                                "Cara",
                                "Parte nº.",
                                "Série",
                                "Construção do país",
                                "Ano de construção",
                                "Mês de construção",
                                "Sociedade",
                                "Ativos fixos",
                                "Centro de custo",
                                "Descrição do centro de custo",
                                "Site",
                                "Nome do local",
                                "Área",
                                "Descrição da área",
                                "Equipe de ponta",
                                "Designação de equipamento superior",
                                "Localização",
                                "Nome do local",
                                "Potência mecânica",
                                "RPM",
                                "Torque",
                                "Capacidade mecânica máx.",
                                "Capacidade mecânica mínima",
                                "Tipo de energia mecânica",
                                "Fluxo",
                                "Relação mecânica",
                                "Frequência mecânica",
                                "Lubrificante",
                                "Rolamentos",
                                "Tensão",
                                "Frequência elétrica",
                                "Energia elétrica",
                                "Capacidade elétrica máx.",
                                "Capacidade elétrica mínima",
                                "Tipo de energia elétrica",
                                "Eficiência nominal",
                                "Eficiência mínima",
                                "Fator de potência",
                                "Fator de serviço",
                                "Relação elétrica",
                                "Fases",
                                "% Elevação de temperatura",
                                "Volume",
                                "Quadro",
                                "Catálogo Nº.",
                                "Especificação Não.",
                                "Serial",
                                "Peso",
                                "Aula",
                                "Estilo",
                                "Projeto",
                                "Vibração",
                                "Avião 1",
                                "Avião 2",
                                "Avião 3",
                                "Criado por",
                                "Modificado por",
                                "Data de criação",
                                "Data de modificação"};

        String[] columnasRU = {"Оборудование",
                                "Номинал",
                                "Статус",
                                "Описание статуса",
                                "Парень",
                                "Описание типа",
                                "Приоритет",
                                "Приоритет описания",
                                "Бренд",
                                "Модель",
                                "Ряд",
                                "Дата изготовления",
                                "Размеры",
                                "Прошедшая дата Серв.",
                                "Стоимость приобретения",
                                "Валюта",
                                "Дата приобретения",
                                "Производитель",
                                "Парень",
                                "Номер детали.",
                                "Ряд",
                                "Дачное строительство",
                                "Год постройки",
                                "Месяц строительства",
                                "Общество",
                                "Основные средства",
                                "центр затрат",
                                "Описание центра затрат",
                                "Сайт",
                                "Название местоположения",
                                "Область",
                                "Описание района",
                                "Лучшая команда",
                                "Название топового оборудования",
                                "Расположение",
                                "Название местоположения",
                                "Механическая мощность",
                                "об/мин",
                                "Крутящий момент",
                                "Макс. механическая мощность",
                                "Мин. емкость механика",
                                "Тип механической энергии",
                                "Поток",
                                "Механическое соотношение",
                                "Механическая частота",
                                "Смазка",
                                "Подшипники",
                                "Напряжение",
                                "Электрическая частота",
                                "Электроэнергия",
                                "Макс. электрическая мощность",
                                "Мин. емкость электрический",
                                "Тип электрической энергии",
                                "Номинальная эффективность",
                                "Минимальная эффективность",
                                "Коэффициент мощности",
                                "Коэффициент обслуживания",
                                "Электрическое соотношение",
                                "Фазы",
                                "% отметки. Темп.",
                                "Объем",
                                "Рамка",
                                "Каталожный номер.",
                                "№ Спецификация",
                                "Серийный",
                                "Масса",
                                "Сорт",
                                "Стиль",
                                "Дизайн",
                                "Вибрация",
                                "Самолет 1",
                                "Самолет 2",
                                "План 3",
                                "Создано",
                                "Изменено",
                                "Дата создания",
                                "Дата модификации",
                                };
        
         String[] columnasDE = {"Ausrüstung",
                                "Konfession",
                                "Status",
                                "Statusbeschreibung",
                                "Kerl",
                                "Typbeschreibung",
                                "Priorität",
                                "Beschreibungspriorität",
                                "Marke",
                                "Modell",
                                "Serie",
                                "Herstellungsdatum",
                                "Abmessungen",
                                "Vergangenes Datum Serv.",
                                "Anschaffungswert",
                                "Währung",
                                "Erwerbsdatum",
                                "Hersteller",
                                "Kerl",
                                "Teile-Nr.",
                                "Serie",
                                "Landbau",
                                "Baujahr",
                                "Baumonat",
                                "Gesellschaft",
                                "Anlagevermögen",
                                "Kostenstelle",
                                "Beschreibung der Kostenstelle",
                                "Website",
                                "Standortname",
                                "Bereich",
                                "Gebietsbeschreibung",
                                "Top-Team",
                                "Top-Gerätename",
                                "Standort",
                                "Standortname",
                                "Mechanische Kraft",
                                "U/min.",
                                "Drehmoment",
                                "Max. mechanische Kapazität",
                                "Mindestkapazität Mechanik",
                                "Mechanischer Energietyp",
                                "Fließen",
                                "Mechanisches Verhältnis",
                                "Mechanische Frequenz",
                                "Schmiermittel",
                                "Lager",
                                "Stromspannung",
                                "Elektrische Frequenz",
                                "Elektrische Energie",
                                "Max. elektrische Kapazität",
                                "Mindestkapazität elektrisch",
                                "Art der elektrischen Energie",
                                "Bewerteter Wirkungsgrad",
                                "Minimaler Wirkungsgrad",
                                "Leistungsfaktor",
                                "Servicefaktor",
                                "Elektrisches Verhältnis",
                                "Phasen",
                                "% Elev. Temp.",
                                "Volumen",
                                "Rahmen",
                                "Katalog-Nr.",
                                "Nr. Spezifikation",
                                "Seriell",
                                "Gewicht",
                                "Klasse",
                                "Stil",
                                "Design",
                                "Vibration",
                                "Flugzeug 1",
                                "Flugzeug 2",
                                "Plan 3",
                                "Erstellt von",
                                "Geändert von",
                                "Erstellungsdatum",
                                "Änderungsdatum",
                                };                  


            modelo.setColumnIdentifiers(columnasEN);
            tabla.setModel(modelo);

    }

}
