
package com.simplecore.erp.server.config.database.oldtables;


public enum almacenes {
    
CODIGO_ALMACEN,
DESCRIPCION_ALMACEN,
ID_TIPO_ALMACEN,
DESCRIPCION_TIPO_ALMACEN,
ID_CLASE_ALMACEN,
DESCRIPCION_CLASE_ALMACEN,
ID_ESTATUS_MATERIAL,
DESCRIPCION_ESTATUS,
ID_AREA_MATERIAL,
DESCRIPCION_AREA_MATERIAL,
ID_COMPANIA,
DESCRIPCION_COMPANIA
    
}
