
package com.simplecore.erp.server.config.database.oldtables;


public enum arbol {
    
NODO_ID_TRANSACCION,
NODO_PRINCIPAL,
MODULOS_ES,
MODULOS_EN,
MODULOS_FR,
MODULOS_PT,
MODULOS_RU,
NODO_DESCRIPCION_TRANSACCION_ES,
NODO_DESCRIPCION_TRANSACCION_EN,
NODO_DESCRIPCION_TRANSACCION_FR,
NODO_DESCRIPCION_TRANSACCION_PT,
NODO_DESCRIPCION_TRANSACCION_RU
;   
}
