
package com.simplecore.erp.server.config.database.oldtables;


public enum operaciones_por_ordenes {
    
NUM_ORDEN,
DESCRIPCION_ORDEN,
NUM_OPERACION,
DESCRIPCION_OPERACION,
CANTIDAD_OPERACION,
COSTO_UNITARIO,
UNIDAD_MEDIDA,
ID_TIPO_OPERACION,
TIPO_OPERACION,
DURACION,
MONTO_TOTAL,
REGISTRO,
CONTEO
    
}
